server:
  port: 9090

spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/demo1?serverTimezone=GMT%2b8
  username: root
  password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
 # configuration:
 #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/IDEA_Work/SpringBoot_Vue_Learning/files/